version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
    networks:
      - birdsong-net
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "$MYSQL_PORT:3306"
    volumes:
      - $DATA_DIR/$MYSQL_DATABASE:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=$TZ
    user: "990032:93098"
    restart: unless-stopped
    networks:
          - $MYSQL_DATABASE-net
  app:
    image: birdsong
    restart: unless-stopped
    depends_on:
      - db
    volumes:
        - ./api:/api
    environment:
      - TZ=$TZ
      - PYTHONUNBUFFERED=1
    networks:
        - birdsong-net
    ports:
      - 84:8000

networks:
  birdsong-net:
      driver: bridge

volumes:
  static_volume:
